remote_theme: Jekyll_modern-blog
# Site settings
title: test Blog
description: test blog, Tools for web development
keywords: test blog Web Development
author: tester
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: none
